### PR TITLE
remove python-microservice-* repos from build pipeline

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Thomas,

This PR removes python-microservice-* repos from OSS build pipeline (all jobs) as issue #88 .

Thank you,
Ngoan

### CODE REVIEW

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Ngoan,
Thank you for your pull-request.
hm... I want to build python-microservice* and test with result in WebApp.
Only:
- documentation should be not in maindoc
- pypi publish we don't do

Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi Ngoan,
> Thank you for your pull-request.
> hm... I want to build python-microservice* and test with result in WebApp.
> Only:
> - documentation should be not in maindoc
> - pypi publish we don't do
> 
> Thank you,
>  Thomas

Hi Thomas,

I observe that the implementation of them are empty now. So that I also removed them from build and test.

Would I bring them back? I will add new commit if requires.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
yes, I would like to let the repos in the build and test chain, so that as soon as something is released to the develop branch it will be built and tested.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
Hi Thomas,

I bring them back now.
I am creating according PR for Gitlab.

Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
very good!
Thank you,
 Thomas

**Pull request merged**
