### PR TITLE
Update documents for adding a new component.

### PR DESCRIPTION
**Pull request by huavanthong**
Hi Thomas,

As your suggestion, I have created the pull request for this documents. https://github.com/test-fullautomation/RobotFramework_AIO/issues/291
Please help me review it

Thank you and best regards,
Thong Hua

### CODE REVIEW

**Review by HolQue — COMMENTED** [review]
Hi Thong,

a tiny hint only: My current understanding is that this document is for us, the developers of the framework, and not for end users. It is a checklist for ourselves and shall help us to manage a process that becomes more and more complicated. But the choice of words still indicates that someone outside our group is the intended audience.

Therefore phrases line "_It will help us_" and "_Please (update)_" should be removed. ;-)

**Comment by huavanthong** [comment]
Hi @HolQue 

Thank you for your hints. I have updated it to be clearer.

Best regards,
Thong Hua

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi @huavanthong ,

can you please convert this file into rst.
It was my mistake to request MarkDown for this filel.

Our input is always rst, then we convert if required to md.

Thank you,
 Thomas

**Comment by huavanthong** [comment]
Hi Thomas,

I have converted it following your comment.

Best regards,
Thong Hua

**Review by test-fullautomation — APPROVED** [review]
Hi Thong,
Looks good to me!
Thank you,
 Thomas

**Pull request merged**
