### PR TITLE
Implement a solution to skip creating a pull request

### PR DESCRIPTION
**Pull request by huavanthong**
Hi Thomas,

As a result in the pipeline when we trigger a tag for release https://github.com/test-fullautomation/RobotFramework_AIO/actions/runs/7626832924
, the job **Update Version AIO** failed because there is already an existing pull request.

Therefore, I would like to update the solution to skip creating the pull request while ensuring that the job is still PASS and the value is still updated to the latest.

Enhancement ticket: https://github.com/test-fullautomation/RobotFramework_AIO/issues/158

If you have any concerns, please tell me.

Thank you,
Thong Hua

### CODE REVIEW

**Review by ngoan1608 — CHANGES_REQUESTED** [review]
Hi Thong,

Skipping creating PR makes the version info is not updated properly.
I have an idea that instead of create a concrete branch `automation/task/update_controlfile_version` which will cause the current issue, we create a dynamic branch name base on our version info such as `automation/task/update_controlfile_version_0.10.0.0`. 
We will not face such issue as current issue (PR request from same branch) and further issue with existence of same branch name.

Thank you,
Ngoan

**Comment by ngoan1608** [comment]
> Hi Thong,
> 
> Skipping creating PR makes the version info is not updated properly. I have an idea that instead of create a concrete branch `automation/task/update_controlfile_version` which will cause the current issue, we create a dynamic branch name base on our version info such as `automation/task/update_controlfile_version_0.10.0.0`. We will not face such issue as current issue (PR request from same branch) and further issue with existence of same branch name.
> 
> Thank you, Ngoan

Hi Thong,

I got your idea after the discussion.
The changes is fine for me now.

Thank you for clarification!
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi both,
very good!
@huavanthong  : by when can I get the updated pull-request?
Thank you,
 Thomas

**Review by test-fullautomation — APPROVED** [review]

**Comment by huavanthong** [comment]
Hi Thomas,

When pushing a tag by named **/dev/aio/x.x.x.x** or **/rel/aio/x.x.x.x** , it will update the pull request with the new version AIO. 
In case a pull request has been created, the process will perform a force push to replace the old value with the new value. Once you consider it okay, you can merge it later.

Thank you,
Thong Hua

**Pull request merged**
