### PR TITLE
Ntd1hc/feat/tag tool is required for oss release

### PR DESCRIPTION
**Pull request by ngoan1608**
Hi Thomas,

The tag tool is not available in Github for OSS build.
The configuration file for tagging has been adapted accordingly to contain all github repos.

The BIOS pipeline is adapted and I am creating pull request for it together with the CT feature.

_Note: An github actions secrets with name **PAT_GITHUB** (which contains the Github PAT - have commit permission on this repo) should be added for authentication._

Thank you,
Ngoan

### CODE REVIEW

**Comment by ngoan1608** [comment]
Hi Thomas,

This PR can be merged together with PR in Gitlab and the new github action secret **_PAT_GITHUB_** as I mentioned above.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
very good!
We integrate this for version 0.8.0.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi Ngoan, very good! We integrate this for version 0.8.0. Thank you, Thomas

Hi Thomas,

This PR and gitlab PR have a relationship.
In case you want to let this PR request for version 0.8.0, I have to remove the commits (related to this PR) in the Gitlab PR, too.
With the changes due to this feature, gitlab CI job will only tag the internal repos and Github action (this new job) will tag all Github repos.

If the gitlab Pr is merged without this change, the OSS pipline will be impacted due to missing tag for cloning and building in github repos.

Thank you,
Ngoan

**Comment by test-fullautomation** [comment]
Hi Ngoan,
please solve the merge conflict.
Thank you,
 Thomas

**Comment by ngoan1608** [comment]
> Hi Ngoan, please solve the merge conflict. Thank you, Thomas

Hi Thomas,

The conflict has been solved with new commit.

Thank you,
Ngoan

**Review by test-fullautomation — APPROVED** [review]
Hi Ngoan,
looks good to me now.
Thank you,
 Thomas

**Pull request merged**
