### PR TITLE
Agt2hc/feat/80/plantuml plugin for vs codium

### PR DESCRIPTION
**Pull request by tranhoangnguyen193**
- This pull request contain fixes for these issues:
   + https://github.com/test-fullautomation/robotframework-testsuitesmanagement/issues/104 overwrite version number for testsuit management
    + https://github.com/test-fullautomation/RobotFramework_AIO/issues/86 draw io extensions
    + https://github.com/test-fullautomation/RobotFramework_AIO/issues/80 plantuml extensions

### CODE REVIEW

**Comment by tranhoangnguyen193** [comment]
Add GENDOC_PLANTUML to the installer too.

**Comment by test-fullautomation** [comment]
Hi Nguyen,
thank you for the pull-request.
Please inform me once you commited the update for  GENDOC_PLANTUML as part of the installers (Win, Linux)
Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Nguyen,
please refer to my review finding.
Thank you,
 Thomas

**Review by test-fullautomation — CHANGES_REQUESTED** [review]
Hi Nguyen,

looks good for me!

What about the GENDOC_PLANTUML_PATH for Linux?

Thank you,
 Thomas

**Pull request merged**
